//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 9 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `background`.
    var background: ColorResource { .init(name: "background", path: [], bundle: bundle) }

    /// Color `blackLabel`.
    var blackLabel: ColorResource { .init(name: "blackLabel", path: [], bundle: bundle) }

    /// Color `divider`.
    var divider: ColorResource { .init(name: "divider", path: [], bundle: bundle) }

    /// Color `grayLabel`.
    var grayLabel: ColorResource { .init(name: "grayLabel", path: [], bundle: bundle) }

    /// Color `grayProgress`.
    var grayProgress: ColorResource { .init(name: "grayProgress", path: [], bundle: bundle) }

    /// Color `green`.
    var green: ColorResource { .init(name: "green", path: [], bundle: bundle) }

    /// Color `lightGray`.
    var lightGray: ColorResource { .init(name: "lightGray", path: [], bundle: bundle) }

    /// Color `purple`.
    var purple: ColorResource { .init(name: "purple", path: [], bundle: bundle) }

    /// Color `segmentedGray`.
    var segmentedGray: ColorResource { .init(name: "segmentedGray", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 16 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `activities`.
    var activities: ImageResource { .init(name: "activities", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `calories`.
    var calories: ImageResource { .init(name: "calories", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `controlActive`.
    var controlActive: ImageResource { .init(name: "controlActive", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `controlNotActive`.
    var controlNotActive: ImageResource { .init(name: "controlNotActive", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `heart`.
    var heart: ImageResource { .init(name: "heart", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `home`.
    var home: ImageResource { .init(name: "home", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `more`.
    var more: ImageResource { .init(name: "more", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `notification`.
    var notification: ImageResource { .init(name: "notification", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onboardingFirst`.
    var onboardingFirst: ImageResource { .init(name: "onboardingFirst", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onboardingSecond`.
    var onboardingSecond: ImageResource { .init(name: "onboardingSecond", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onboardingThird`.
    var onboardingThird: ImageResource { .init(name: "onboardingThird", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `profile`.
    var profile: ImageResource { .init(name: "profile", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sleep`.
    var sleep: ImageResource { .init(name: "sleep", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `status`.
    var status: ImageResource { .init(name: "status", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `walk`.
    var walk: ImageResource { .init(name: "walk", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `water`.
    var water: ImageResource { .init(name: "water", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }
}